name: Java CI

on:
    push:
        branches:
            - test-actions

jobs:
    build:
        strategy:
            matrix:
                java: [8]

        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres
                ports:
                    - 5432
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: 'postgres'
                    POSTGRES_DB: test_db
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
            mysql:
                image: mysql:8
                ports:
                    - 3306
                env:
                    MYSQL_ROOT_PASSWORD: root
                options: >-
                    --health-cmd "mysqladmin ping"
                    --health-interval 5s
                    --health-timeout 2s
                    --health-retries 3

        steps:
            - uses: actions/checkout@v2.3.4

            - name: Restore dependency cache
              uses: actions/cache@v2.1.3
              with:
                  path: ~/.m2/repository
                  key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                  restore-keys: |
                      ${{ runner.os }}-maven-

            - name: Set up Java ${{ matrix.java }}
              uses: actions/setup-java@v1
              with:
                  java-version: ${{ matrix.java }}
